### ISSUE TITLE
Should optionally allow white

### ISSUE THREAD

**Issue by cheapsteak** [mattdesl/get-rgba-palette#2]
https://github.com/mattdesl/get-rgba-palette/blob/master/index.js#L50

I think this should be an option that you can turn off

```js
if (!(r > 250 && g > 250 && b > 250)) {
```

Sometimes you want white to be one of the colors in the palette

**Comment by mattdesl** [comment]
Yeah true. I think that line should be removed and alpha threshold should be configurable:

```js
getRgbaPalette(pixels, count, quality, alphaThreshold)
```

Or maybe change to `opt` to future-proof the API?

```js
getRgbaPalette(pixels, { count, quality, alphaThreshold })
```

User can always pre-process `pixels` if they want to remove white/black from the results.

**Comment by mattdesl** [comment]
Another idea: allow a `filter` function instead of threshold parameter, and have it default to:

```js
function filter (color, index, array) {
    return color[3] >= 125
}
```

**Comment by cheapsteak** [comment]
+1 on filter  
definitely the most robust

**Comment by mattdesl** [comment]
you wanna PR?

**Comment by mattdesl** [comment]
closing, adedd filter and removed the white thing
