### ISSUE TITLE
Question about bitwise operators

### ISSUE THREAD

**Issue by zeke** [mattdesl/get-rgba-palette#6]
Bitwise operators are mysterious to me. What is this code doing? Rounding numbers down if they're not integers?

```js
count = typeof count === 'number' ? (count|0) : 5
quality = typeof quality === 'number' ? (quality|0) : 10
```

**Comment by mattdesl** [comment]
The bitwise OR is a truncation. Converts float to integer - also turning NaN, non finite and non numbers to zero. You will sometimes also see `~~foo` which is the same. It doesn't handle big numbers because of overflow. 

Probably would have been clearer if I used Math.trunc (ES6) or Math.floor.
